apiVersion: apps/v1
kind: Deployment
metadata:
  name: iperf
  namespace: openshift-monitoring
spec:
  replicas: 1 # Set to the number of parallel clients you want to run
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: iperf
  template:
    metadata:
      labels:
        app.kubernetes.io/name: iperf
      name: iperf
      namespace: openshift-monitoring
    spec:
      containers:
        - args:
            - --client
            - 172.16.110.8 # IP address of the host where iperf3 server is running. Must go through IPSec
            - --time
            - "0"
            - --zerocopy
            - --bidir
            - --bitrate
            - "$(BITRATE)"
            - --interval
            - "1" # seconds between each interval
            - --parallel
            - "$(CONNECTION_COUNT)"
          image: quay.io/jmoller/iperf3:static
          env:
            - name: BITRATE
              value: "200M" # Adjust the Bitrate
            - name: CONNECTION_COUNT
              value: "64" # Adjust the number of parallel connections
          imagePullPolicy: IfNotPresent
          name: iperf3
#          ports:
#            - containerPort: 5201
#              hostPort: 5201
#              name: iperf
#              protocol: TCP
      dnsPolicy: ClusterFirstWithHostNet
      enableServiceLinks: true
      hostNetwork: true
      hostPID: true
      nodeSelector:
        kubernetes.io/os: linux
      priorityClassName: system-cluster-critical
      restartPolicy: Always
      securityContext:
        runAsNonRoot: false
      serviceAccountName: node-exporter
      terminationGracePeriodSeconds: 10